version: '3.7'

services:
  web:
    build: ./services/app
    command: python server.py
    volumes:
      - ./services/app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spotify

volumes:
  postgres_data: