version: '3.7'

services:
  web:
    build: ./services/app
    command: python server.py
    volumes:
      - ./services/app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev