version: '3.7'

services:
  web:
    build: ./services/app
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - ./.env.db.prod
  nginx:
    build: ./services/nginx
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data: