name: CD

on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: PGPASSWORD
          script: |
            cd /home/kristiancharb/spotipath-app
            git checkout master && git pull
            docker-compose -f docker-compose.prod.yml down -v
            docker-compose -f docker-compose.prod.yml up -d --build
            sleep 5
            zcat ~/spotify_dump.gz | gunzip | psql -h 127.0.0.1 --username=postgres --dbname=spotify